"""Consolidated sysctl composer — single source for /etc/sysctl.d/99-kyth-*.conf.

Reads build_files/config/sysctl/{base,gaming,network}.toml typed inputs and
emits base + network always, plus gaming when populated (gaming empty → no
file to avoid stale header-only). Fails on duplicate key across tiers
(duplicate was the CAKE/bbr silent clobber bug before).

Pattern mirrors kyth_shared/gaming_resolve.py single-source and
sched_autogroup.py atomic tmp→replace.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import tomllib  # py311+
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore[no-redef]

# Resolve config dir relative to this file, with fallbacks for build container
_CANDIDATES = [
    Path(__file__).resolve().parents[2] / "config" / "sysctl",
    Path("/ctx/config/sysctl"),
    Path("/usr/share/kyth/config/sysctl"),
]

TIERS = ("base", "gaming", "network")
OUTPUTS = {
    "base": Path("/etc/sysctl.d/99-kyth-base.conf"),
    "gaming": Path("/etc/sysctl.d/99-kyth-gaming.conf"),
    "network": Path("/etc/sysctl.d/99-kyth-network.conf"),
}
LEGACY = Path("/etc/sysctl.d/99-kyth.conf")
HEADER = "# Generated by kyth_shared.sysctl_compose — do not edit directly. Source: build_files/config/sysctl/*.toml\n"


def _config_dir(explicit: Path | None = None) -> Path:
    if explicit is not None:
        return Path(explicit)
    for p in _CANDIDATES:
        if p.is_dir():
            return p
    return _CANDIDATES[0]


def _load_tier(tier: str, config_dir: Path) -> dict[str, tuple[str, str]]:
    """Return {key: (value, comment)} for tier, empty if file missing or has no keys."""
    path = config_dir / f"{tier}.toml"
    if not path.is_file():
        return {}
    try:
        with path.open("rb") as f:
            data = tomllib.load(f)
    except (OSError, ValueError, RuntimeError, AttributeError, KeyError) as e:  # noqa: BLE001 -- narrow: best-effort production path
        raise SystemExit(f"sysctl_compose: failed to parse {path}: {e}") from e
    keys = data.get("keys", {})
    if not isinstance(keys, dict):
        return {}
    out: dict[str, tuple[str, str]] = {}
    for k, v in keys.items():
        if not isinstance(v, dict):
            continue
        val = str(v.get("value", "")).strip()
        if not val:
            continue
        comment = str(v.get("comment", "")).strip()
        out[str(k).strip()] = (val, comment)
    return out


def load_inputs(config_dir: Path | None = None) -> dict[str, dict[str, tuple[str, str]]]:
    cd = _config_dir(config_dir)
    return {tier: _load_tier(tier, cd) for tier in TIERS}


def lint_no_duplicates(inputs: dict[str, dict[str, tuple[str, str]]]) -> list[str]:
    seen: dict[str, str] = {}
    dups: list[str] = []
    for tier in TIERS:
        for key in inputs.get(tier, {}):
            if key in seen:
                dups.append(f"duplicate key {key!r} in tiers {seen[key]!r} and {tier!r}")
            else:
                seen[key] = tier
    return dups


def _render_tier(keys: dict[str, tuple[str, str]]) -> str:
    lines = [HEADER]
    for k in sorted(keys):
        val, comment = keys[k]
        if comment:
            lines.append(f"{k} = {val}  # {comment}")
        else:
            lines.append(f"{k} = {val}")
    return "\n".join(lines) + "\n" if len(lines) > 1 else HEADER


def compose(config_dir: Path | None = None) -> dict[str, str]:
    cd = _config_dir(config_dir)
    inputs = load_inputs(cd)
    dups = lint_no_duplicates(inputs)
    if dups:
        raise SystemExit("sysctl_compose: duplicate keys:\n" + "\n".join(dups))
    return {tier: _render_tier(inputs[tier]) for tier in TIERS}


def emit_all(config_dir: Path | None = None, dest_root: Path | None = None) -> list[Path]:
    cd = _config_dir(config_dir)
    inputs = load_inputs(cd)
    dups = lint_no_duplicates(inputs)
    if dups:
        raise SystemExit("sysctl_compose: duplicate keys:\n" + "\n".join(dups))
    written: list[Path] = []
    for tier in TIERS:
        dest = (dest_root / OUTPUTS[tier].name) if dest_root else OUTPUTS[tier]
        # gaming tier empty → no file; prevents stale header-only file from being active
        if tier == "gaming" and not inputs[tier]:
            try:
                if dest.exists():
                    dest.unlink()
            except OSError:
                pass
            continue
        content = _render_tier(inputs[tier])
        dest.parent.mkdir(parents=True, exist_ok=True)
        tmp = dest.with_suffix(".tmp")
        tmp.write_text(content, encoding="utf-8")
        tmp.replace(dest)
        written.append(dest)
    # Remove legacy monolith if present — it is now generated via tiers
    try:
        if LEGACY.exists() and LEGACY not in written:
            LEGACY.unlink()
    except OSError:
        pass
    # Remove legacy per-tunable 99-kyth-*.conf files now covered by tiers (Slice 6)
    # These shadow the composed base/network/gaming files via lexical sort.
    legacy_globs = [
        "99-kyth-swappiness.conf",
        "99-kyth-compaction.conf",
        "99-kyth-dirty-expire.conf",
        "99-kyth-dirty-ratio.conf",
        "99-kyth-inotify-watches.conf",
        "99-kyth-max-map-count.conf",
        "99-kyth-sched-autogroup.conf",
        "99-kyth-vfs-cache.conf",
        "99-kyth-vm-stat.conf",
        "99-kyth-vm-watermark.conf",
        "99-kyth-vm-compaction.conf",
        "99-kyth-net-tune.conf",
        "99-kyth-net-backlog.conf",
        "99-kyth-rmem-max.conf",
        "99-kyth-wmem-max.conf",
        "99-kyth-busy-poll.conf",
        "99-kyth-busy-read.conf",
        "99-kyth-sched-child.conf",
        "99-kyth-sched-nr-migrate.conf",
        "99-kyth-tcp-*.conf",
        "99-kyth-psi-poll.conf",
        "99-kyth-page-cluster.conf",
    ]
    import fnmatch

    dest_dir = dest_root if dest_root else Path("/etc/sysctl.d")
    for pat in legacy_globs:
        for p in dest_dir.glob(pat):
            # never delete the three tier files themselves
            if p.name in ("99-kyth-base.conf", "99-kyth-gaming.conf", "99-kyth-network.conf"):
                continue
            try:
                p.unlink()
            except OSError:
                pass
    # Guard: fail if dead config/sysctl.conf still exists in image context
    dead = Path("/ctx/config/sysctl.conf")
    if dead.is_file():
        raise SystemExit(f"sysctl_compose: dead file {dead} still present — migrate keys to base.toml then delete")
    return written


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Kyth consolidated sysctl composer")
    ap.add_argument("--config-dir", type=Path, default=None, help="override config/sysctl dir")
    ap.add_argument("--dest-root", type=Path, default=None, help="emit to this dir (for tests)")
    ap.add_argument("--check", action="store_true", help="lint duplicates only, do not write")
    ap.add_argument("--emit-all", action="store_true", help="emit all three tier files")
    ap.add_argument("--cat", choices=TIERS, help="print rendered tier to stdout")
    args = ap.parse_args(argv)

    if args.check:
        inputs = load_inputs(args.config_dir)
        dups = lint_no_duplicates(inputs)
        if dups:
            for d in dups:
                print(d, file=sys.stderr)
            return 1
        print("sysctl_compose: no duplicate keys")
        return 0

    if args.cat:
        rendered = compose(args.config_dir)
        sys.stdout.write(rendered[args.cat])
        return 0

    if args.emit_all or args.dest_root:
        emit_all(args.config_dir, args.dest_root)
        return 0

    # default: check
    inputs = load_inputs(args.config_dir)
    dups = lint_no_duplicates(inputs)
    if dups:
        for d in dups:
            print(d, file=sys.stderr)
        return 1
    print("sysctl_compose: ok (use --emit-all to write)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
