/* Shared mutable state for the installer workflow. */
globalThis.KythInstallerState = {
  disk: null,
  install_mode: 'wipe',
  target_partition: null,
  resize_partition: null,
  resize_gib: 64,
  free_region_start: 0,
  free_region_end: 0,
  hostname: 'kyth',
  timezone: 'UTC',
  locale: 'en_US.UTF-8',
  keymap: 'us',
  username: '',
  password: '',
  kernel: 'fedora',
  isLive: true,
  disks: [],
  partitions: [],
  freeRegions: [],
  minGuidedGiB: 32,
  replaceAllowed: true,
  pendingOps: [],
  supportedFilesystems: [],
  manualCommitted: false,
  startTime: 0,
  elapsedTimer: null,
};
