"""Tests for consolidated sysctl composer."""

import tempfile
import unittest
from pathlib import Path

from kyth_shared.sysctl_compose import compose, emit_all, lint_no_duplicates, load_inputs


class TestSysctlCompose(unittest.TestCase):
    def test_no_duplicates_default(self):
        inputs = load_inputs(Path("build_files/config/sysctl"))
        dups = lint_no_duplicates(inputs)
        self.assertEqual(dups, [], f"duplicate keys found: {dups}")

    def test_expected_keys_present(self):
        rendered = compose(Path("build_files/config/sysctl"))
        # base should contain VM + kernel keys
        self.assertIn("vm.swappiness", rendered["base"])
        self.assertIn("vm.dirty_bytes", rendered["base"])
        self.assertIn("vm.max_map_count", rendered["base"])
        self.assertIn("kernel.nmi_watchdog", rendered["base"])
        # network should contain BBR + qdisc + backlog
        self.assertIn("net.ipv4.tcp_congestion_control", rendered["network"])
        self.assertIn("net.core.default_qdisc", rendered["network"])
        self.assertIn("net.core.netdev_max_backlog", rendered["network"])
        # migrated keys
        self.assertIn("vm.extfrag_threshold", rendered["base"])
        self.assertIn("net.ipv4.tcp_ecn", rendered["network"])
        self.assertIn("fs.file-max", rendered["base"])

    def test_gaming_header_only_when_empty(self):
        rendered = compose(Path("build_files/config/sysctl"))
        # gaming starts empty — should be header only
        self.assertTrue(rendered["gaming"].startswith("# Generated"))

    def test_duplicate_detection(self):
        inputs = {
            "base": {"vm.swappiness": ("180", "x")},
            "network": {"vm.swappiness": ("60", "y")},
            "gaming": {},
        }
        dups = lint_no_duplicates(inputs)
        self.assertEqual(len(dups), 1)
        self.assertIn("vm.swappiness", dups[0])

    def test_emit_all_to_dest_root(self):
        with tempfile.TemporaryDirectory() as td:
            dest = Path(td)
            written = emit_all(Path("build_files/config/sysctl"), dest)
            # gaming empty → only base + network (2 files); header-only stale file avoided
            self.assertEqual(len(written), 2)
            names = {p.name for p in written}
            self.assertEqual(names, {"99-kyth-base.conf", "99-kyth-network.conf"})
            for p in written:
                self.assertTrue(p.is_file())
                text = p.read_text(encoding="utf-8")
                self.assertIn("# Generated by", text)
            # no gaming file when empty
            self.assertFalse((dest / "99-kyth-gaming.conf").exists())
            # check no duplicate across emitted files
            all_keys: dict[str, str] = {}
            for p in written:
                for line in p.read_text().splitlines():
                    if "=" in line and not line.startswith("#"):
                        k = line.split("=")[0].strip()
                        self.assertNotIn(k, all_keys, f"duplicate {k} across emitted files")
                        all_keys[k] = str(p)
            # at least 30 keys overall
            self.assertGreater(len(all_keys), 30)
        # when gaming has keys, all three are emitted
        with tempfile.TemporaryDirectory() as td:
            cfg = Path(td) / "cfg"
            cfg.mkdir()
            # minimal base + network + gaming
            (cfg / "base.toml").write_text('[keys."vm.swappiness"]\nvalue="10"\n', encoding="utf-8")
            (cfg / "network.toml").write_text('[keys."net.ipv4.tcp_ecn"]\nvalue="1"\n', encoding="utf-8")
            (cfg / "gaming.toml").write_text('[keys."kernel.sched_autogroup_enabled"]\nvalue="0"\n', encoding="utf-8")
            with tempfile.TemporaryDirectory() as dd:
                dest2 = Path(dd)
                written2 = emit_all(cfg, dest2)
                self.assertEqual(len(written2), 3)
                self.assertTrue((dest2 / "99-kyth-gaming.conf").is_file())

    def test_dead_sysctl_conf_removed(self):
        self.assertFalse(Path("build_files/config/sysctl.conf").exists(), "dead config/sysctl.conf should be deleted")

    def test_legacy_fragments_no_sysctl_writes(self):
        for rel in [
            "build_files/scripts/sysconfig/network/51-tcp-bbr-tuning.sh",
            "build_files/scripts/sysconfig/network/56-network-cake.sh",
            "build_files/scripts/sysconfig/kernel/55-vm-compaction-tuning.sh",
        ]:
            text = Path(rel).read_text(encoding="utf-8")
            self.assertNotIn("write_config /etc/sysctl.d", text, f"{rel} should not write sysctl directly")
        self.assertNotIn("cp /ctx/data/sysctl.d/99-kyth.conf", Path("build_files/scripts/sysconfig/kernel/01-kernel-sysctl-parameters.sh").read_text())

    def test_base_supersedes_dead_max_map_count(self):
        rendered = compose(Path("build_files/config/sysctl"))
        # dead had 2147483642, shipped should be 16777216
        self.assertIn("vm.max_map_count = 16777216", rendered["base"])
        self.assertNotIn("vm.max_map_count = 2147483642", rendered["base"])
