"""Tests for consolidated sysctl composer."""

import tempfile
import unittest
from pathlib import Path

from kyth_shared.sysctl_compose import compose, emit_all, lint_no_duplicates, load_inputs


class TestSysctlCompose(unittest.TestCase):
    def test_no_duplicates_default(self):
        inputs = load_inputs(Path("build_files/config/sysctl"))
        dups = lint_no_duplicates(inputs)
        self.assertEqual(dups, [], f"duplicate keys found: {dups}")

    def test_expected_keys_present(self):
        rendered = compose(Path("build_files/config/sysctl"))
        # base should contain VM + kernel keys
        self.assertIn("vm.swappiness", rendered["base"])
        self.assertIn("vm.dirty_bytes", rendered["base"])
        self.assertIn("vm.max_map_count", rendered["base"])
        self.assertIn("kernel.nmi_watchdog", rendered["base"])
        # network should contain BBR + qdisc + backlog
        self.assertIn("net.ipv4.tcp_congestion_control", rendered["network"])
        self.assertIn("net.core.default_qdisc", rendered["network"])
        self.assertIn("net.core.netdev_max_backlog", rendered["network"])
        # migrated keys
        self.assertIn("vm.extfrag_threshold", rendered["base"])
        self.assertIn("net.ipv4.tcp_ecn", rendered["network"])
        self.assertIn("fs.file-max", rendered["base"])

    def test_gaming_header_only_when_empty(self):
        rendered = compose(Path("build_files/config/sysctl"))
        # Slice 3: gaming now populated (11 keys from 10 wrappers) — header + keys
        self.assertTrue(rendered["gaming"].startswith("# Generated"))
        # when gaming has keys it should contain consolidated gaming overrides
        self.assertIn("fs.aio-max-nr", rendered["gaming"])
        self.assertIn("kernel.sched_bore", rendered["gaming"])
        self.assertIn("net.core.busy_poll", rendered["gaming"])

    def test_duplicate_detection(self):
        inputs = {
            "base": {"vm.swappiness": ("180", "x")},
            "network": {"vm.swappiness": ("60", "y")},
            "gaming": {},
        }
        dups = lint_no_duplicates(inputs)
        self.assertEqual(len(dups), 1)
        self.assertIn("vm.swappiness", dups[0])

    def test_emit_all_to_dest_root(self):
        with tempfile.TemporaryDirectory() as td:
            dest = Path(td)
            written = emit_all(Path("build_files/config/sysctl"), dest)
            # Slice 3: gaming now populated → all 3 tiers emitted (base+gaming+network)
            self.assertEqual(len(written), 3)
            names = {p.name for p in written}
            self.assertEqual(names, {"99-kyth-base.conf", "99-kyth-gaming.conf", "99-kyth-network.conf"})
            for p in written:
                self.assertTrue(p.is_file())
                text = p.read_text(encoding="utf-8")
                self.assertIn("# Generated by", text)
            # gaming now has keys
            gaming_text = (dest / "99-kyth-gaming.conf").read_text(encoding="utf-8")
            self.assertIn("fs.aio-max-nr", gaming_text)
            # check no duplicate across emitted files
            all_keys: dict[str, str] = {}
            for p in written:
                for line in p.read_text().splitlines():
                    if "=" in line and not line.startswith("#"):
                        k = line.split("=")[0].strip()
                        self.assertNotIn(k, all_keys, f"duplicate {k} across emitted files")
                        all_keys[k] = str(p)
            # at least 30 keys overall
            self.assertGreater(len(all_keys), 30)
        # when gaming has keys, all three are emitted
        with tempfile.TemporaryDirectory() as td:
            cfg = Path(td) / "cfg"
            cfg.mkdir()
            # minimal base + network + gaming
            (cfg / "base.toml").write_text('[keys."vm.swappiness"]\nvalue="10"\n', encoding="utf-8")
            (cfg / "network.toml").write_text('[keys."net.ipv4.tcp_ecn"]\nvalue="1"\n', encoding="utf-8")
            (cfg / "gaming.toml").write_text('[keys."kernel.sched_autogroup_enabled"]\nvalue="0"\n', encoding="utf-8")
            with tempfile.TemporaryDirectory() as dd:
                dest2 = Path(dd)
                written2 = emit_all(cfg, dest2)
                self.assertEqual(len(written2), 3)
                self.assertTrue((dest2 / "99-kyth-gaming.conf").is_file())

    def test_dead_sysctl_conf_removed(self):
        self.assertFalse(Path("build_files/config/sysctl.conf").exists(), "dead config/sysctl.conf should be deleted")

    def test_legacy_fragments_no_sysctl_writes(self):
        for rel in [
            "build_files/scripts/sysconfig/network/51-tcp-bbr-tuning.sh",
            "build_files/scripts/sysconfig/network/56-network-cake.sh",
            "build_files/scripts/sysconfig/kernel/55-vm-compaction-tuning.sh",
        ]:
            text = Path(rel).read_text(encoding="utf-8")
            self.assertNotIn("write_config /etc/sysctl.d", text, f"{rel} should not write sysctl directly")
        self.assertNotIn("cp /ctx/data/sysctl.d/99-kyth.conf", Path("build_files/scripts/sysconfig/kernel/01-kernel-sysctl-parameters.sh").read_text())

    def test_base_supersedes_dead_max_map_count(self):
        rendered = compose(Path("build_files/config/sysctl"))
        # dead had 2147483642, shipped should be 16777216
        self.assertIn("vm.max_map_count = 16777216", rendered["base"])
        self.assertNotIn("vm.max_map_count = 2147483642", rendered["base"])

    def test_gaming_slice3_keys(self):
        rendered = compose(Path("build_files/config/sysctl"))
        gaming = rendered["gaming"]
        # Slice 3+4: 26 wrappers → 31 keys (bore 2, sched-latency 5)
        expected = {
            "fs.aio-max-nr": "1048576",
            "kernel.sched_bore": "1",
            "kernel.sched_bore_burst_penalty_offset": "12",
            "net.core.busy_poll": "50",
            "net.core.busy_read": "50",
            "vm.min_free_kbytes": "131072",
            "net.core.netdev_budget": "600",
            "kernel.numa_balancing": "0",
            "vm.overcommit_memory": "1",
            "kernel.perf_cpu_time_max_percent": "5",
            "net.core.rmem_default": "262144",
            # Slice 4: 16 wrappers / 20 keys
            "vm.pressure_poll": "500",
            "kernel.sched_child_runs_first": "0",
            "kernel.sched_latency_ns": "6000000",
            "kernel.sched_min_granularity_ns": "1000000",
            "kernel.sched_wakeup_granularity_ns": "1000000",
            "kernel.sched_migration_cost_ns": "500000",
            "kernel.sched_nr_migrate": "32",
            "net.core.somaxconn": "8192",
            "net.ipv4.tcp_fin_timeout": "30",
            "net.ipv4.tcp_keepalive_time": "120",
            "net.ipv4.tcp_no_metrics_save": "1",
            "net.ipv4.tcp_notsent_lowat": "16384",
            "net.ipv4.tcp_orphan_retries": "0",
            "net.ipv4.tcp_retries1": "3",
            "net.ipv4.tcp_retries2": "8",
            "net.ipv4.tcp_sack": "1",
            "net.ipv4.tcp_timestamps": "1",
            "net.ipv4.tcp_window_scaling": "1",
            "kernel.khugepaged_defrag": "0",
            "net.core.wmem_default": "262144",
        }
        for k, v in expected.items():
            self.assertIn(f"{k} = {v}", gaming, f"missing {k}")
        # exactly 31 key lines
        key_lines = [l for l in gaming.splitlines() if "=" in l and not l.startswith("#")]
        self.assertEqual(len(key_lines), len(expected))
        # no duplicates across tiers
        inputs = load_inputs(Path("build_files/config/sysctl"))
        dups = lint_no_duplicates(inputs)
        self.assertEqual(dups, [])
