"""Clean Perf card for PerformancePage."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .page_performance import PerformancePage


def make_clean_card(page: "PerformancePage"):
    from .qt import QHBoxLayout, QLabel, QPushButton
    from .widgets import _make_card

    clean_card, clean_layout = _make_card()
    clean_title = QLabel("Clean Perf — zero cost when off")
    clean_title.setObjectName("card-title")
    clean_layout.addWidget(clean_title)
    clean_desc = QLabel(
        "Kargs/I/O/Net/UKSmd/Journal + THP/Mimalloc/IRQ/Btrfs/Trim — off by default, TOML in /etc/kyth, revertible."
    )
    clean_desc.setObjectName("card-copy")
    clean_desc.setWordWrap(True)
    clean_layout.addWidget(clean_desc)
    clean_row = QHBoxLayout()
    clean_row.setSpacing(8)
    page._clean_status = QLabel("Clean perf: checking…")
    page._clean_status.setObjectName("prop-val-dim")
    clean_row.addWidget(page._clean_status, 1)
    btn_kargs = QPushButton("Kargs")
    btn_kargs.setToolTip("kargs.toml profile balanced/performance/gaming (mitigations=off only in gaming)")
    btn_kargs.clicked.connect(page._clean_kargs_status)
    clean_row.addWidget(btn_kargs)
    btn_io = QPushButton("I/O")
    btn_io.clicked.connect(lambda: page._run_clean("io"))
    clean_row.addWidget(btn_io)
    btn_net = QPushButton("Net")
    btn_net.clicked.connect(lambda: page._run_clean("net"))
    clean_row.addWidget(btn_net)
    btn_uksmd = QPushButton("UKSmd")
    btn_uksmd.clicked.connect(lambda: page._run_clean("uksmd"))
    clean_row.addWidget(btn_uksmd)
    btn_journal = QPushButton("Journal")
    btn_journal.clicked.connect(lambda: page._run_clean("journal"))
    clean_row.addWidget(btn_journal)
    clean_layout.addLayout(clean_row)
    clean_row2 = QHBoxLayout()
    clean_row2.setSpacing(8)
    clean_row2.addWidget(QLabel(""), 1)
    btn_thp = QPushButton("THP")
    btn_thp.clicked.connect(lambda: page._run_clean("thp"))
    clean_row2.addWidget(btn_thp)
    btn_mimalloc = QPushButton("Mimalloc")
    btn_mimalloc.clicked.connect(lambda: page._run_clean("mimalloc"))
    clean_row2.addWidget(btn_mimalloc)
    btn_irq = QPushButton("IRQ")
    btn_irq.clicked.connect(lambda: page._run_clean("irq"))
    clean_row2.addWidget(btn_irq)
    btn_btrfs = QPushButton("Btrfs")
    btn_btrfs.clicked.connect(lambda: page._run_clean("btrfs"))
    clean_row2.addWidget(btn_btrfs)
    btn_trim = QPushButton("Trim")
    btn_trim.clicked.connect(lambda: page._run_clean("trim"))
    clean_row2.addWidget(btn_trim)
    clean_layout.addLayout(clean_row2)
    clean_row3 = QHBoxLayout()
    clean_row3.setSpacing(8)
    clean_row3.addWidget(QLabel(""), 1)
    btn_ananicy = QPushButton("Ananicy")
    btn_ananicy.clicked.connect(lambda: page._run_clean("ananicy"))
    clean_row3.addWidget(btn_ananicy)
    btn_zswap = QPushButton("Zswap")
    btn_zswap.clicked.connect(lambda: page._run_clean("zswap"))
    clean_row3.addWidget(btn_zswap)
    btn_gpu = QPushButton("GPU")
    btn_gpu.clicked.connect(lambda: page._run_clean("gpu"))
    clean_row3.addWidget(btn_gpu)
    btn_sched = QPushButton("Sched")
    btn_sched.clicked.connect(lambda: page._run_clean("sched"))
    clean_row3.addWidget(btn_sched)
    btn_readahead = QPushButton("Readahead")
    btn_readahead.clicked.connect(lambda: page._run_clean("readahead"))
    clean_row3.addWidget(btn_readahead)
    clean_layout.addLayout(clean_row3)
    clean_row4 = QHBoxLayout()
    clean_row4.setSpacing(8)
    btn_master = QPushButton("MASTER Gaming")
    btn_master.setObjectName("primary")
    btn_master.setToolTip("gaming-performance.toml one toggle for 46-60 (kargs/io/thp/irq/btrfs/trim/ananicy/zswap/sched/net)")
    btn_master.clicked.connect(lambda: page._run_clean("master"))
    clean_row4.addWidget(btn_master)
    btn_wine = QPushButton("WineSync")
    btn_wine.clicked.connect(lambda: page._run_clean("wine"))
    clean_row4.addWidget(btn_wine)
    btn_kwin = QPushButton("KWin")
    btn_kwin.clicked.connect(lambda: page._run_clean("kwin"))
    clean_row4.addWidget(btn_kwin)
    btn_pipe = QPushButton("PipeWG")
    btn_pipe.clicked.connect(lambda: page._run_clean("pipewire"))
    clean_row4.addWidget(btn_pipe)
    btn_bauto = QPushButton("BtrfsAuto")
    btn_bauto.clicked.connect(lambda: page._run_clean("btrfsauto"))
    clean_row4.addWidget(btn_bauto)
    clean_layout.addLayout(clean_row4)
    clean_row5 = QHBoxLayout()
    clean_row5.setSpacing(8)
    btn_boot = QPushButton("Boot0")
    btn_boot.setToolTip("loader.toml fast 0s vs balanced 2s")
    btn_boot.clicked.connect(lambda: page._run_clean("boot"))
    clean_row5.addWidget(btn_boot)
    btn_oomg = QPushButton("OOM-G")
    btn_oomg.clicked.connect(lambda: page._run_clean("oomg"))
    clean_row5.addWidget(btn_oomg)
    btn_shader = QPushButton("ShaderTmp")
    btn_shader.clicked.connect(lambda: page._run_clean("shader"))
    clean_row5.addWidget(btn_shader)
    btn_cfs = QPushButton("CFS")
    btn_cfs.clicked.connect(lambda: page._run_clean("cfs"))
    clean_row5.addWidget(btn_cfs)
    btn_audit = QPushButton("Audit")
    btn_audit.setObjectName("primary")
    btn_audit.clicked.connect(lambda: page._run_clean("audit"))
    clean_row5.addWidget(btn_audit)
    clean_layout.addLayout(clean_row5)
    return clean_card
