#!/usr/bin/env python3
import os, re, shutil, subprocess

aprc = os.path.expanduser("~/.config/plasma-org.kde.plasma.desktop-appletsrc")
autostart = os.path.expanduser("~/.config/autostart/kyth-set-kickoff-icon.desktop")
kwriteconfig = shutil.which('kwriteconfig6')

if kwriteconfig:
    subprocess.run([
        kwriteconfig, '--file', 'kickoffrc',
        '--group', 'General',
        '--key', 'highlightNewlyInstalledApps',
        '--type', 'bool', 'false',
    ], check=False)

if kwriteconfig and os.path.exists(aprc):
    content = open(aprc).read()
    for m in re.finditer(
        r'^\[Containments\]\[(\d+)\]\[Applets\]\[(\d+)\]',
        content, re.MULTILINE
    ):
        cont, applet = m.group(1), m.group(2)
        body_start = m.end()
        nxt = re.search(r'^\[', content[body_start:], re.MULTILINE)
        body = content[body_start: body_start + nxt.start()] if nxt else content[body_start:]
        if 'plugin=org.kde.plasma.kickoff' in body:
            subprocess.run([
                kwriteconfig, '--file', aprc,
                '--group', 'Containments', '--group', cont,
                '--group', 'Applets', '--group', applet,
                '--group', 'Configuration', '--group', 'General',
                '--key', 'icon', 'kyth-kickoff',
            ], check=False)
            subprocess.run([
                kwriteconfig, '--file', aprc,
                '--group', 'Containments', '--group', cont,
                '--group', 'Applets', '--group', applet,
                '--group', 'Configuration', '--group', 'General',
                '--key', 'highlightNewlyInstalledApps',
                '--type', 'bool', 'false',
            ], check=False)

try:
    os.unlink(autostart)
except OSError:
    pass
