#!/usr/bin/env python3
"""kyth-refresh-taskbar-pins wrapper."""
import sys



from kyth_shared.desktop.plasma import refresh_taskbar_pins  # noqa: E402


def main() -> None:
    sys.exit(refresh_taskbar_pins())


if __name__ == "__main__":
    main()
