#!/usr/bin/env python3
"""kyth-apply-desktop-layout wrapper."""
import sys



from kyth_shared.desktop.plasma import apply_desktop_layout  # noqa: E402


def main() -> None:
    force = False
    initial = False
    for arg in sys.argv[1:]:
        if arg == "--force":
            force = True
        elif arg == "--initial":
            initial = True
        elif arg in ("-h", "--help"):
            print("Usage: kyth-apply-desktop-layout [--initial|--force]")
            sys.exit(0)

    sys.exit(apply_desktop_layout(force=force, initial=initial))


if __name__ == "__main__":
    main()
