#!/bin/bash
# shellcheck shell=bash
set -euo pipefail

# ── irqbalance Tuning ────────────────────────────────────────────────────────
# Configures irqbalance to avoid migrating interrupts across CPU cache domains (CCDs),
# preventing cache invalidation and inter-CCD latency (critical for multi-CCD / Ryzen X3D CPUs).
mkdir -p /etc/sysconfig
cat >/etc/sysconfig/irqbalance <<'EOF'
# Generated by KythOS
IRQBALANCE_ARGS="--deepestcache=2"
EOF
